### ISSUE TITLE
Set compiler version in CI to 0.10.2 when it comes out

### ISSUE THREAD

**Issue by gballet** [gballet/zig-rlp#2]
In #1 we set the compiler version in CI to zig's `master`. This isn't great because the tests might pass at some point and no longer do at a later time, which would be confusing to users of this library. We are currently using functions in `build.zig` that should land in 0.10.2, so let's replace `master` with `0.10.2` in `.github/workflows/ci.yml` when it comes out.

The step reporting the compiler version should then also be removed as it is no longer necessary.

**Comment by jsign** [comment]
Done by https://github.com/gballet/zig-rlp/commit/540bc9741a052ef56f57105fa392139f0979d99c
